name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to Ferrari-OS!! , thanks for raising the issue , checkout contributing guidelines to understand how the community works, We are so happy to have you here!!"
        pr-message: "Welcome to Ferrari-OS!!, congrats on your first PR"
